# Generated by Django 5.1.3 on 2024-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_time',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_date',
            field=models.DateField(null=True, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_location',
            field=models.TextField(default='NA', verbose_name='Delivery Location'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DELIVERY', 'Delivery')], max_length=10, null=True, verbose_name='Order Type'),
        ),
    ]
