# Generated by Django 5.1.3 on 2024-11-21 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_delivery_time_and_more'),
        ('restaurants', '0003_pickuplocation_timeslots_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='restaurants.pickuplocation'),
        ),
        migrations.AddField(
            model_name='orders',
            name='time_slots',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='time_slots', to='restaurants.timeslots'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_PREPARING', 'Order Preparing'), ('PACKED', 'Packed'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('SHIPPED', 'Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='ORDER_PLACED', max_length=20),
        ),
    ]
