# Generated by Django 5.1.3 on 2024-11-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_pickup_location_orders_time_slots_and_more'),
        ('restaurants', '0007_remove_timeslots_code_remove_timeslots_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='time_slots',
        ),
        migrations.AddField(
            model_name='orders',
            name='deliverydate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurants.workingdays', verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.CharField(help_text='In Australian Dollars', max_length=50, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Time'),
        ),
    ]
