# Generated by Django 5.1.3 on 2024-11-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orders_pickup_location_orders_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.CharField(help_text='In Australian Dollars', max_length=50, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Order Time'),
        ),
    ]
