# Generated by Django 5.1.3 on 2024-11-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_amount_alter_orders_order_time'),
        ('orders', '0004_remove_orders_delivery_date_remove_orders_time_slots_and_more'),
    ]

    operations = [
    ]
