# Generated by Django 5.1.3 on 2024-12-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orders_deliverydate_orders_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='shipping_charges',
            field=models.CharField(help_text='In Australian Dollars', max_length=50, null=True, verbose_name='Shipping Charges'),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.CharField(help_text='In Australian Dollars', max_length=50, null=True, verbose_name='Total Order price'),
        ),
    ]
