# Generated by Django 5.1.3 on 2024-12-18 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_notes'),
        ('transactions', '0009_alter_ordercoupon_desc_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.ordercoupon', verbose_name='Coupon applied'),
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.CharField(default='0', help_text='In Australian Dollars', max_length=50, verbose_name='Total Discount Applied'),
        ),
    ]
