# Generated by Django 5.1.3 on 2024-12-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orders_coupon_orders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='before_tax',
            field=models.CharField(default='0', help_text='In Australian Dollars', max_length=50, verbose_name='Total Before Tax'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tax',
            field=models.CharField(default='0', help_text='In Australian Dollars', max_length=50, verbose_name='Total Tax'),
        ),
    ]
