# Generated by Django 5.1.3 on 2024-11-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in US dollars', max_digits=8),
        ),
    ]
