# Generated by Django 5.1.3 on 2024-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orders_delivery_time_and_more'),
        ('restaurants', '0002_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pickup Location Name')),
                ('code', models.UUIDField(unique=True, verbose_name='Pickup Location Code')),
                ('street_address1', models.CharField(max_length=255, verbose_name='Street Address')),
                ('street_address2', models.CharField(max_length=255, verbose_name='Street Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
            ],
            options={
                'verbose_name': 'PickupLocation',
                'verbose_name_plural': 'PickupLocations',
            },
        ),
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='Time Slot')),
                ('code', models.CharField(max_length=50, verbose_name='Time Slot Code')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
            },
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
