# Generated by Django 5.1.3 on 2024-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_pickuplocation_timeslots_delete_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price in  Australian dollars', max_digits=8),
        ),
    ]
