# Generated by Django 5.1.3 on 2024-11-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_menuitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortionSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Portion Size')),
                ('weight', models.CharField(help_text='Weight in grams', max_length=50, verbose_name='Portion Weight')),
            ],
            options={
                'verbose_name': 'Portion Size',
                'verbose_name_plural': 'Portion Sizes',
                'ordering': ['weight'],
            },
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Menu Item Name'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(help_text='Price in  Australian dollars', max_length=50, verbose_name='Menu Item Price'),
        ),
        migrations.CreateModel(
            name='MenuPortionPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(help_text='Price in  Australian dollars', max_length=50, verbose_name='Portion Price')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items_prices', to='restaurants.menuitem', verbose_name='Menu Item')),
                ('portion_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_size_prices', to='restaurants.portionsize', verbose_name='Portion Item')),
            ],
            options={
                'verbose_name': 'Menu Portion Price Lists',
                'ordering': ['id'],
            },
        ),
    ]
