# Generated by Django 5.1.3 on 2024-11-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_portionsize_alter_menuitem_name_alter_menuitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Addon Name')),
                ('price', models.CharField(help_text='Price in  Australian dollars', max_length=50, verbose_name='Addon Price')),
            ],
            options={
                'verbose_name': 'Addon',
                'verbose_name_plural': 'Addons',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='portion_sizes',
            field=models.ManyToManyField(help_text='Select Portion', to='restaurants.portionsize', verbose_name='Menu Items Sizes'),
        ),
    ]
