# Generated by Django 5.1.3 on 2024-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_addons_menuitem_portion_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='code',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslots',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='timeslots',
            name='type',
            field=models.CharField(choices=[('ALL', 'All'), ('DELIVERY ONLY', 'Delivery Only'), ('PICKUP ONLY', 'Pickup Only')], max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='WorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('time_slot', models.ManyToManyField(related_name='working_days', to='restaurants.timeslots', verbose_name='Time Slot')),
            ],
        ),
    ]
