# Generated by Django 5.1.3 on 2024-11-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_timeslots_code_remove_timeslots_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addons',
            options={'ordering': ['name'], 'verbose_name': 'Menu Dishes Addon', 'verbose_name_plural': 'Menu Dishes Addons'},
        ),
        migrations.AlterModelOptions(
            name='menuimage',
            options={'ordering': ['-is_main'], 'verbose_name': 'Menu Dish Image', 'verbose_name_plural': 'Menu Dishes Images'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['name'], 'verbose_name': 'Menu Dish', 'verbose_name_plural': 'Menu Dishes'},
        ),
        migrations.AlterModelOptions(
            name='menuportionpricelist',
            options={'ordering': ['id'], 'verbose_name': 'Price List', 'verbose_name_plural': 'Price Lists'},
        ),
    ]
