# Generated by Django 5.1.3 on 2024-11-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_addons_options_alter_menuimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingdays',
            options={'verbose_name': 'Kitchen Open Day', 'verbose_name_plural': 'Kitchen Open Days'},
        ),
    ]
