# Generated by Django 5.1.3 on 2024-11-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_addons_options_alter_menuimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workingdays',
            options={'verbose_name': 'Kitchen Open Day', 'verbose_name_plural': 'Kitchen Open Days'},
        ),
        migrations.AddField(
            model_name='portionsize',
            name='addons',
            field=models.ManyToManyField(to='restaurants.addons', verbose_name=''),
        ),
        migrations.AddField(
            model_name='portionsize',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Portion Code'),
        ),
    ]
