# Generated by Django 5.1.3 on 2024-11-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_workingdays_options_portionsize_addons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AlterField(
            model_name='portionsize',
            name='addons',
            field=models.ManyToManyField(blank=True, to='restaurants.addons', verbose_name='Any Addons'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='tags',
            field=models.ManyToManyField(to='restaurants.menuitemtags', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(to='restaurants.menucategory', verbose_name='Categories'),
        ),
    ]
