# Generated by Django 5.1.3 on 2024-11-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_alter_workingdays_options'),
        ('restaurants', '0010_menuitemtags_remove_menuitem_category_and_more'),
    ]

    operations = [
    ]
