# Generated by Django 5.1.3 on 2024-11-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_merge_20241126_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemtags',
            options={'verbose_name': 'Item Tag', 'verbose_name_plural': 'Item Tags'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='portion_sizes',
        ),
    ]
