# Generated by Django 5.1.3 on 2024-11-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_menuitemtags_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_best_selling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuportionpricelist',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='menuportionpricelist',
            name='carbs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuportionpricelist',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='menuportionpricelist',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
