# Generated by Django 5.1.3 on 2024-12-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_menuitem_is_best_selling_menuitem_is_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery location name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in  Australian dollars', max_digits=5, verbose_name='Delivery Charges')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
            ],
            options={
                'verbose_name': 'Delivery Point',
                'verbose_name_plural': 'Delivery Points',
            },
        ),
        migrations.AddField(
            model_name='pickuplocation',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in  Australian dollars', max_digits=5, null=True, verbose_name='Pickup charges'),
        ),
    ]
