# Generated by Django 5.1.3 on 2024-12-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0014_deliverypoint_pickuplocation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='trans_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Translation Code'),
        ),
    ]
