# Generated by Django 5.1.3 on 2024-12-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0016_menuitem_trans_desc_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menuportionpricelist',
            unique_together={('menu_item', 'portion_item')},
        ),
    ]
