# Generated by Django 5.1.3 on 2024-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_menuportionpricelist_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.CharField(blank=True, help_text='Price in  Australian dollars', max_length=50, null=True, verbose_name='Menu Item Price'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='trans_code',
            field=models.CharField(blank=True, help_text='Note: If you modify this make sure to update translations.', max_length=255, null=True, verbose_name='Translation Code'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='trans_desc_code',
            field=models.CharField(blank=True, help_text='Note: If you modify this make sure to update translations.', max_length=255, null=True, verbose_name='Translation Description Code'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price in  Australian dollars', max_digits=5, null=True, verbose_name='Pickup charges'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='street_address1',
            field=models.CharField(max_length=255, verbose_name='Street Address 1'),
        ),
        migrations.AlterField(
            model_name='pickuplocation',
            name='street_address2',
            field=models.CharField(max_length=255, verbose_name='Street Address 2'),
        ),
    ]
