# Generated by Django 5.1.3 on 2024-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Feature')),
                ('feature_code', models.CharField(default=None, max_length=255, unique=True, verbose_name='Feature Code')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label Code')),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], max_length=20, verbose_name='Language')),
                ('value', models.CharField(blank=True, default=None, max_length=255, verbose_name='Language Translation ')),
                ('feature', models.ManyToManyField(blank=True, to='translations.languagecategory', verbose_name='Features')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'ordering': ['id'],
            },
        ),
    ]
