# Generated by Django 5.1.3 on 2024-11-23 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255, verbose_name='Page Name')),
                ('feature_code', models.CharField(max_length=255, unique=True, verbose_name='Page Code')),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='translation',
            name='feature',
        ),
        migrations.AlterField(
            model_name='translation',
            name='value',
            field=models.CharField(blank=True, default=None, max_length=255, verbose_name='Language Translation'),
        ),
        migrations.AddField(
            model_name='translation',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='translations.module', verbose_name='Pages'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LanguageCategory',
        ),
    ]
