# Generated by Django 5.1.3 on 2024-11-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0002_module_remove_translation_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='translations.module', verbose_name='Pages'),
        ),
    ]
