# Generated by Django 5.1.3 on 2024-11-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='unique_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='Unique Wallet ID'),
        ),
    ]
