# Generated by Django 5.1.3 on 2024-11-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street_address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='is_billing',
            field=models.BooleanField(default=False, verbose_name='Billing'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street_address1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address1'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street_address2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Street Address2'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='suburbs',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Suburbs'),
        ),
    ]
