# Generated by Django 5.1.3 on 2024-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], max_length=10)),
                ('discount_upto', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Order Coupon',
                'verbose_name_plural': 'Order Coupons',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_type', models.CharField(choices=[('WALLET_RECHARGE', 'Wallet Recharge'), ('FOOD_ORDER', 'Food Order')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('transaction_from', models.CharField(choices=[('WALLET', 'Wallet'), ('STRIPE', 'Stripe')], max_length=10)),
                ('operation_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WalletCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recharge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recharge_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Wallet Coupon',
                'verbose_name_plural': 'Wallet Coupons',
                'ordering': ['-id'],
            },
        ),
    ]
