# Generated by Django 5.1.3 on 2024-12-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoupon',
            name='desc_code',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='walletcoupon',
            name='desc_code',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='walletcoupon',
            name='name_code',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Discount Percentage'), ('FIXED_ITEM', 'Fixed discount per Item'), ('FIXED_ORDER', 'Fixed discount per Order')], max_length=15),
        ),
    ]
