# Generated by Django 5.1.3 on 2024-12-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_ordercoupon_desc_code_walletcoupon_desc_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletcoupon',
            name='name_code',
        ),
        migrations.AddField(
            model_name='ordercoupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='walletcoupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
    ]
