# Generated by Django 5.1.3 on 2024-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_remove_walletcoupon_name_code_ordercoupon_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercoupon',
            name='name_code',
            field=models.CharField(default='na', max_length=50, verbose_name='Coupon Name Translation Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='desc_code',
            field=models.CharField(default='NA', max_length=200, verbose_name='Coupon Description Translation Code'),
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='discount_upto',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Discount'),
        ),
    ]
