# Generated by Django 5.1.3 on 2024-12-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_ordercoupon_name_code_alter_ordercoupon_desc_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoupon',
            name='desc_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Coupon Description Translation Code'),
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='name_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Coupon Name Translation Code'),
        ),
    ]
