# Generated by Django 5.1.3 on 2024-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_ordercoupon_desc_code_alter_ordercoupon_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercoupon',
            name='desc_code',
            field=models.CharField(max_length=200, unique=True, verbose_name='Description Translation Code'),
        ),
        migrations.AlterField(
            model_name='ordercoupon',
            name='name_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name Translation Code'),
        ),
    ]
